[[main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = -100
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name = "Обо мне"
    url = "/page/about/"
    weight = -90
    [main.params]
        icon = "user"

[[main]]
    identifier = "archives"
    name = "Архив"
    url = "/page/archives/"
    weight = -70
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name = "Поиск"
    url = "/page/search/"
    weight = -60
    [main.params]
        icon = "search"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/username"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "telegram"
    name = "Telegram"
    url = "https://t.me/username"
    [social.params]
        icon = "brand-telegram"

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/username"
    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "email"
    name = "Email"
    url = "mailto:user@example.com"
    [social.params]
        icon = "mail"